image:
  repository: ghcr.io/traefik/whoami
  pullPolicy: IfNotPresent
  tag: v1.11.0@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
service:
  main:
    enabled: true
    ports:
      main:
        port: 8080
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
