image:
  repository: ghcr.io/traefik/whoami
  pullPolicy: IfNotPresent
  tag: v1.11.0@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - --port
            - "8080"
service:
  main:
    enabled: true
    ports:
      main:
        port: 8080
        targetPort: 8080
redis:
  enabled: false
mariadb:
  enabled: false
mongodb:
  enabled: false
